name: E2E Tests
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Escolha o navegador de sua preferência para os testes (chromium, firefox, webkit)'
        required: true
        default: 'chromium'
      base_url:
        description: 'Escolha o ambiente de testes de sua preferência (local, homolog, production)'
        required: true
        default: 'http://localhost:3000'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: checkout Code
      uses: actions/checkout@v5

    - name: Node Setup
      uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ github.event.inputs.browser }}

    - name: Run E2E tests
      run: BASE_URL=${{ github.event.inputs.base_url }} npx playwright test --project=${{ github.event.inputs.browser }}
      
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ github.event.inputs.browser }}
        path: playwright-report/
        retention-days: 30